apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: srs-password-policy
  description: SRS Service Portal Cloudeka (Password Policy)
  tags: ["srs"]
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Lintasarta/srs-password_policy-v1.0
    # PERHATIKAN INDENTASI: Baris di bawah if harus sejajar dengan github.com...
spec:
  type: service
  lifecycle: production
  owner: user:default/afi
